name: dragonball_heroes
description: "Cino case study"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  dart_mappable: ^4.6.1
  dio: ^5.9.0
  envied: ^1.3.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^9.1.1
  go_router: ^17.0.0
  injectable: ^2.7.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  transparent_image: ^2.0.1

dev_dependencies:
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.1
  envied_generator: ^1.3.2
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.11.2
  leancode_lint: ^19.0.1
  mockito: ^5.4.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
